### ISSUE TITLE
[Question] 原理是啥？

### ISSUE THREAD

**Issue by zhuozhiyongde** [xiaotianxt/fxxk-pku-treehole#1]
草，看到恢复删除的树洞有点好奇，瞅了眼代码似乎是修改 HTTP 响应？怎么说，难道树洞被删了后端正常回复，只是修改 Status Code？

**Comment by xiaotianxt** [comment]
不行的，而且建议不要轻易尝试，我已经被封号了🐶

我的想法仅仅是拦截请求做一个持久化存储，在之后刷新的时候把消失的数据插入进去。代码还比较简陋，但是现在被封号了没法继续开发了，尽量悠着点（

**Comment by zhuozhiyongde** [comment]
草 那没事了 想起来大一做的PKU News和PKU Treehole Backup也是这个思路，高强度请求（逃
（后来被封号约谈一条龙了

**Comment by xiaotianxt** [comment]
> 草 那没事了 想起来大一做的PKU News和PKU Treehole Backup也是这个思路，高强度请求（逃 （后来被封号约谈一条龙了

哈哈哈，那我还是先不乱搞了，自己偷摸用
